@api= http://localhost:4000/usuarios


GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
    "FK_idRol": 2,
    "Correo": "test@gmail.com",
    "Contraseña": "1234",
    "Activo": 1
    
}